- Updated yml - Added web config file

diff --git a/.github/workflows/main_umsehdhub.yml b/.github/workflows/main_umsehdhub.yml
--- a/.github/workflows/main_umsehdhub.yml
+++ b/.github/workflows/main_umsehdhub.yml
@@ -29,14 +29,15 @@ jobs:
           npm run build --if-present
           npm run test --if-present
 
-      - name: Zip artifact for deployment
-        run: zip -r release.zip dist
+      - name: Copy web.config to dist folder
+        run: |
+          cp public/web.config dist/ || echo "web.config not found, skipping copy"
 
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: node-app
-          path: release.zip
+          path: dist
 
   deploy:
     runs-on: ubuntu-latest
@@ -51,14 +52,11 @@ jobs:
         with:
           name: node-app
 
-      - name: Unzip artifact for deployment
-        run: unzip release.zip -d .
-      
       - name: 'Deploy to Azure Web App'
         id: deploy-to-webapp
         uses: azure/webapps-deploy@v3
         with:
           app-name: 'umsehdhub'
           slot-name: 'Production'
-          package: dist
+          package: .
           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B88EB2A821454ABFAC101AFF29BB0E36 }}
